/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ksi.tugas.pertemuan5;

import javax.swing.JOptionPane;

/**
 * @author
 * Anggota Kelompok:
 * 10119028 - Rizal Sihombing
 * 10119038 - Rachman Aldiansyah
 * 10119042 - Muhammad Rifqu Abdillah
 */
public class frmCipherCaesar extends javax.swing.JFrame {

    public frmCipherCaesar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEncrypt = new javax.swing.JLabel();
        lblinputTeks1 = new javax.swing.JLabel();
        txt_inputTeks1 = new javax.swing.JTextField();
        txt_pergeseran1 = new javax.swing.JTextField();
        lblpergeseran = new javax.swing.JLabel();
        btn_prosesEncrypt = new javax.swing.JButton();
        lblHasilEncrypt = new javax.swing.JLabel();
        txt_hasilTeks1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblDecrypt = new javax.swing.JLabel();
        txt_inputTeks2 = new javax.swing.JTextField();
        lblinputTeks2 = new javax.swing.JLabel();
        lbl_nilaiPergeseran = new javax.swing.JLabel();
        txt_pergeseran2 = new javax.swing.JTextField();
        lbl_hasilTeks = new javax.swing.JLabel();
        txt_hasilTeks2 = new javax.swing.JTextField();
        btn_prosesDecrypt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(726, 502));

        lblEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEncrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncrypt.setText("ENCRYPT");

        lblinputTeks1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblinputTeks1.setText("Masukan Teks");

        lblpergeseran.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblpergeseran.setText("Nilai Pergeseran");

        btn_prosesEncrypt.setText("Proses");
        btn_prosesEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesEncryptActionPerformed(evt);
            }
        });

        lblHasilEncrypt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHasilEncrypt.setText("Hasil Teks");

        lblDecrypt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDecrypt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDecrypt.setText("DECRYPT");

        lblinputTeks2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblinputTeks2.setText("Masukan Teks");

        lbl_nilaiPergeseran.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_nilaiPergeseran.setText("Nilai Pergeseran");

        lbl_hasilTeks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_hasilTeks.setText("Hasil Teks");

        btn_prosesDecrypt.setText("Proses");
        btn_prosesDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesDecryptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncrypt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(lblDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHasilEncrypt)
                            .addComponent(lblinputTeks1)
                            .addComponent(lblpergeseran))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_hasilTeks1)
                            .addComponent(txt_inputTeks1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_prosesEncrypt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_pergeseran1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_hasilTeks)
                    .addComponent(lblinputTeks2)
                    .addComponent(lbl_nilaiPergeseran))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_hasilTeks2)
                    .addComponent(txt_inputTeks2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_prosesDecrypt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_pergeseran2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEncrypt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_inputTeks1)
                    .addComponent(lblinputTeks1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pergeseran1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpergeseran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_prosesEncrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHasilEncrypt)
                    .addComponent(txt_hasilTeks1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_inputTeks2)
                    .addComponent(lblinputTeks2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pergeseran2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nilaiPergeseran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_prosesDecrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_hasilTeks)
                    .addComponent(txt_hasilTeks2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prosesEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesEncryptActionPerformed
        String masukan_encrypt = txt_inputTeks1.getText().toLowerCase();
        int pergeseran = Integer.parseInt(txt_pergeseran1.getText());
    
        if ((masukan_encrypt).equals("")){
        JOptionPane.showMessageDialog(null, "Teks tidak boleh kosong! Silahkan coba lagi");
        } else {
            String alpha = "abcdefghijklmnopqrstuvwxyz";
            String cipherText = "";
            for (int ii = 0; ii < masukan_encrypt.length(); ii++) {
              int charPosition = alpha.indexOf(masukan_encrypt.charAt(ii));
              int keyVal = (pergeseran + charPosition) % 26;
              char replaceVal = alpha.charAt(keyVal);
              cipherText += replaceVal;
            }
            txt_hasilTeks1.setText(cipherText);
        }
    }//GEN-LAST:event_btn_prosesEncryptActionPerformed

    private void btn_prosesDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesDecryptActionPerformed
        // Mengambil inputan dari user
        String masukan_decrypt = txt_inputTeks2.getText().toLowerCase();
        int pegeseran_decrypt = Integer.parseInt(txt_pergeseran2.getText());
        
        // Inisialisasi 26 alphabet
        String alpha = "abcdefghijklmnopqrstuvwxyz";
        String decryptText = "";
        for (int i = 0; i < masukan_decrypt.length(); i++){
              
            // Mengambil setiap posisi karakter
            int pos = alpha .indexOf(masukan_decrypt.charAt(i));   
              
            // Mengambil setiap decrypt karakter
            int decryptPos = (pos - pegeseran_decrypt) % 26;
            if (decryptPos < 0){   
                decryptPos = alpha.length() + decryptPos;   
            }   
            char decryptChar = alpha.charAt(decryptPos);   
              
            // Simpan pada variabel
            decryptText += decryptChar;   
        }
        //menampilkan hasil kepada user
        txt_hasilTeks2.setText(decryptText);
    }//GEN-LAST:event_btn_prosesDecryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCipherCaesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCipherCaesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCipherCaesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCipherCaesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCipherCaesar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prosesDecrypt;
    private javax.swing.JButton btn_prosesEncrypt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDecrypt;
    private javax.swing.JLabel lblEncrypt;
    private javax.swing.JLabel lblHasilEncrypt;
    private javax.swing.JLabel lbl_hasilTeks;
    private javax.swing.JLabel lbl_nilaiPergeseran;
    private javax.swing.JLabel lblinputTeks1;
    private javax.swing.JLabel lblinputTeks2;
    private javax.swing.JLabel lblpergeseran;
    private javax.swing.JTextField txt_hasilTeks1;
    private javax.swing.JTextField txt_hasilTeks2;
    private javax.swing.JTextField txt_inputTeks1;
    private javax.swing.JTextField txt_inputTeks2;
    private javax.swing.JTextField txt_pergeseran1;
    private javax.swing.JTextField txt_pergeseran2;
    // End of variables declaration//GEN-END:variables
}
